### ISSUE TITLE
Impossible to RUN POOL WITH THIS COIN

### ISSUE THREAD

**Issue by mounirrquiba** [alloyproject/alloy#2]
Error: Failed to parse block
    at Error (native)
    at Object.BlockTemplate.nextBlob (/root/crypto-sumo/lib/pool.js:131:23)
    at Object.Miner.getJob (/root/crypto-sumo/lib/pool.js:383:41)
    at handleMinerMethod (/root/crypto-sumo/lib/pool.js:606:28)
    at handleMessage (/root/crypto-sumo/lib/pool.js:741:13)
    at Socket.<anonymous> (/root/crypto-sumo/lib/pool.js:795:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)

Problem is from deamon not working good, without any wiki or docs impossible to start new pool...

**Comment by nighthawk18** [comment]
Sounds like you have a config issue. We have a number of pools already running as seen here: http://alloyexplorer.com/#pools

Join our discord and we can help you: http://alloyproject.org/discord
